version: '3'

services:
  mysql-master:
    image: qanah/mysql-replication:5.7-latest
    platform: linux/amd64 # Specify platform for Mac ARM compatibility
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - REPLICATION_SERVER=master
    ports:
      - "3306:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql

  mysql-slave1:
    image: qanah/mysql-replication:5.7-latest
    platform: linux/amd64 # Specify platform for Mac ARM compatibility
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - REPLICATION_SERVER_ID=2
      - REPLICATION_SERVER=slave
      - MASTER_HOST=mysql-master
    ports:
      - "3307:3306"
    volumes:
      - mysql-slave1-data:/var/lib/mysql
    depends_on:
      - mysql-master

  mysql-slave2:
    image: qanah/mysql-replication:5.7-latest
    platform: linux/amd64 # Specify platform for Mac ARM compatibility
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - REPLICATION_SERVER_ID=3
      - REPLICATION_SERVER=slave
      - MASTER_HOST=mysql-master
    ports:
      - "3308:3306"
    volumes:
      - mysql-slave2-data:/var/lib/mysql
    depends_on:
      - mysql-master

volumes:
  mysql-master-data:
  mysql-slave1-data:
  mysql-slave2-data:
