version: '3'

services:
  mysql-source:
    image: qanah/mysql-replication:8.0-latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - REPLICATION_SERVER_ID=1
      - REPLICATION_SERVER=master
    ports:
      - "3306:3306"
    volumes:
      - mysql-source-data:/var/lib/mysql

  mysql-replica1:
    image: qanah/mysql-replication:8.0-latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - REPLICATION_SERVER_ID=2
      - REPLICATION_SERVER=slave
      - MASTER_HOST=mysql-source
    ports:
      - "3307:3306"
    volumes:
      - mysql-replica1-data:/var/lib/mysql
    depends_on:
      - mysql-source

volumes:
  mysql-source-data:
  mysql-replica1-data:
