version: '3'

services:
  mysql-master1:
    image: qanah/mysql-replication:5.7-latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - REPLICATION_SERVER_ID=1
      - REPLICATION_SERVER=master
      - MASTER_HOST=mysql-master2
    ports:
      - "3306:3306"
    volumes:
      - mysql-master1-data:/var/lib/mysql

  mysql-master2:
    image: qanah/mysql-replication:5.7-latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - REPLICATION_SERVER_ID=2
      - REPLICATION_SERVER=master
      - MASTER_HOST=mysql-master1
    ports:
      - "3307:3306"
    volumes:
      - mysql-master2-data:/var/lib/mysql
    depends_on:
      - mysql-master1

volumes:
  mysql-master1-data:
  mysql-master2-data:
